### ISSUE TITLE
Objectifs

### ISSUE THREAD

**Issue by BinaryTiger** [ClubCedille/jardiniot#2]
Ce qu'on cherche a accomplir avec le projet
- Développement durable
- Autosuffisance
- Contribuer publiquement a un projet
- Avoir quelque chose de physique a montrer pour cedille
- Etc

**Comment by AXDOOMER** [comment]
À écrire sur le Wiki si tu veux t'en servir pour faire la promotion du projet. En fait, quelqu'un l'a [déjà fait](https://github.com/ClubCedille/jardiniot/wiki/Objectifs).
