### ISSUE TITLE
Compléter le système embarqué

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/jardiniot#21]
#### Maintenant qu'on peut envoyer des données du DHT au serveur MQTT, la prochaine étape est la suivante: 

~~(Le travail s’effectuera ici: https://github.com/AXDOOMER/jardiniot et résultera en un PR)~~

### À faire (durant le développement)
- [x] Permettre au ESP de recevoir des topics (il peut déjà en envoyer)
    - Un pot a plusieurs topics qui lui sont attachées.
- [x] Implémenter toutes les bonnes topics (consultez https://github.com/ClubCedille/jardiniot/issues/19 comme référence)
    - Humidité, température, contrôle des ventilateurs, contrôle des lumières DEL et autres.

### À faire après le développement (avant le PR)
- [x] Améliorer les commentaires
- [x] Enlever le code mort
- [x] Enlever tout ce qui est inutile (évidemment!)

**Comment by mikefaille** [comment]
Je te propose de faire un pull request par tâche autrement ça l'implique que tu vas travailler tout seul car en principe, un pull request sert à gérer le QA pendant le développement et non après.

**Comment by AXDOOMER** [comment]
### Pour recevoir des topics

Exemples de code:
* http://www.esp8266.com/viewtopic.php?f=29&t=2745
* https://www.baldengineer.com/multiple-mqtt-topics-pubsubclient.html

**Comment by AXDOOMER** [comment]
#### Pour contrôler les lumières

```
void setup() {
  // put your setup code here, to run once:
  pinMode(5, OUTPUT); 
  setPwmFrequency(5, 1);
  pinMode(6, OUTPUT); 
  setPwmFrequency(6, 1);
}

void loop() {
  analogWrite(5, 255);
  analogWrite(6, 255);

}

void setPwmFrequency(int pin, int divisor) {
  byte mode;
  if(pin == 5 || pin == 6 || pin == 9 || pin == 10) {
    switch(divisor) {
      case 1: mode = 0x01; break;
      case 8: mode = 0x02; break;
      case 64: mode = 0x03; break;
      case 256: mode = 0x04; break;
      case 1024: mode = 0x05; break;
      default: return;
    }
    if(pin == 5 || pin == 6) {
      TCCR0B = TCCR0B & 0b11111000 | mode;
    } else {
      TCCR1B = TCCR1B & 0b11111000 | mode;
    }
  } else if(pin == 3 || pin == 11) {
    switch(divisor) {
      case 1: mode = 0x01; break;
      case 8: mode = 0x02; break;
      case 32: mode = 0x03; break;
      case 64: mode = 0x04; break;
      case 128: mode = 0x05; break;
      case 256: mode = 0x06; break;
      case 1024: mode = 0x07; break;
      default: return;
    }
    TCCR2B = TCCR2B & 0b11111000 | mode;
  }
}
```
