### ISSUE TITLE
[SERVEUR] Faire le site/le control panel

### ISSUE THREAD

**Issue by aubguillemette** [ClubCedille/jardiniot#31]
Commencer à faire le site qui va servir de control panel pour le jardin.

**Comment by AXDOOMER** [comment]
Voir [le design du site web](https://github.com/ClubCedille/jardiniot/wiki/Interface-web).

**Comment by AXDOOMER** [comment]
Alexandre Brochu était peut-être intéressé à contribuer aussi, par contre son username est pas disponible pour le taguer ou l'assigner.

**Comment by AXDOOMER** [comment]
Trouvé! @AlexBrochu

**Comment by AXDOOMER** [comment]
### Important

Nous travaillons maintenant avec  [SerreÉTS](http://serreets.com/). Notre système de site web et serveur qui recueillent les données doit être extensible et général. 

Il doit marcher avec n'importe quel senseur, que ce soit pour recueillir des données ou controller un bidule (comme un pompe ou une lumière). 

**On doit pouvoir stoker les données des différents senseurs en indiquant une marge d'erreur**, ceci afin qu'il soit possible d'utiliser les données pour des recherches scientifiques.

**Comment by notarock** [comment]
Le site est dans la version master :+1: 
Pour le moment, Il permet d'afficher les données en temps réel à interval de 1 seconde.

[video](
https://www.youtube.com/watch?v=bx7-ICqu1vo)

**Comment by AXDOOMER** [comment]
Fermé en faveur de https://github.com/ClubCedille/jardiniot/issues/48
