### ISSUE TITLE
[API] Modification du connecteur pour l'envoi de commandes au ESP

### ISSUE THREAD

**Issue by aubguillemette** [ClubCedille/jardiniot#33]
- [x] Renommer connector.js en mqtt_connector.js (ce sera plus évident de distinguer ce que ce fichier fait)
- [x] Convertir le connecteur en module node.js pour qu'il puisse être utilisé comme un module (voir [sqlite_connector.js](https://github.com/ClubCedille/jardiniot/blob/master/serveur-web/api/sqlite_connector.js) à titre d'exemple.
- [x] Ajouter le code pour envoyer des commandes au ESP en se basant sur les spécifications décrites [ici](https://github.com/ClubCedille/jardiniot/wiki/Connectivit%C3%A9-entre-ESP-et-API-(MQTT)).
- [x] Ajouter du code pour pouvoir envoyer des commandes au ESP via une requête HTTP POST
- [ ] Implémenter la structure définie [ici](https://github.com/ClubCedille/jardiniot/wiki/Structure-de-l'API)
- [ ] Implémenter les fonctionnalitées pour chaque méthode HTTP, tel que défini [ici](https://github.com/ClubCedille/jardiniot/wiki/Structure-de-l'API)
- [ ] Restreindre l'envoi de données POST aux utilisateurs authentifiés

**Comment by aubguillemette** [comment]
- [ ] Ajouter du code pour pouvoir "Register" un nouveau bucket dans la base de données (via une requête HTTP POST)

- [ ] Ajouter du code pour envoyer des commandes au ESP (via MQTT, voir le code du connecteur)

**Comment by AXDOOMER** [comment]
@notarock  Je ferme ce issue. Je crois qu'il n'est plus nécessaire, car je crois que tu vas faire ça différemment.

**Comment by AXDOOMER** [comment]
Je vais effacer cette branche aussi. Définitivement trop vieille et abandonnée. 

https://github.com/ClubCedille/jardiniot/tree/feat_connecteur_SubscriberTopicsAuto
