### ISSUE TITLE
[GÉNÉRAL] Choisir une license pour le projet

### ISSUE THREAD

**Issue by aubguillemette** [ClubCedille/jardiniot#40]
- [x] Choisir une license pour le projet
- [x] Créer un fichier LICENSE dans le repo
- [ ] Ajouter la license dans les fichiers package.json

Ci-dessous, j'ai mis un tableau que j'ai pris sur le [blog de Jeff Atwood](https://blog.codinghorror.com), dans l'article [Pick a License, Any License](https://blog.codinghorror.com/pick-a-license-any-license/). Ce tableau peut nous aider à choisir une license convenable pour notre projet.

License|Source|Type (Clauses)|Description
--------|--------|--------|--------
|None|Open|None (0)|Without a license, the code is copyrighted by default. People can read the code, but they have no legal right to use it. To use the code, you must contact the author directly and ask permission.|
|Public domain|Open|Permissive (0)|If your code is in the public domain, anyone may use your code for any purpose whatsoever. Nothing is in the public domain by default; you have to explicitly put your work in the public domain if you want it there. Otherwise, you must be dead a long time before your work reverts to the public domain.|
|GPL|Open|Copyleft (12)|The archetypal bearded, sandal-clad free software license. Your code can never be used in any proprietary program, ever! Take that, capitalism!|
|LGPL|Open|Mostly Copyleft (16)|GPL with a cleverly-constructed pressure valve release. Your free software can be binary linked to proprietary programs under certain very specific circumstances.|
|MIT/X11|Open|Permissive (2)|Short and sweet. Includes generic legal disclaimer of liability.|
|BSD|Open|Permissive (2)|Short and sweet. Includes legal disclaimer of liability with explicitly named organization.|
|Apache|Open|Permissive (9)|Requires derivative works to provide notification of any licensed or proprietary code in a common location.|
|Eclipse|Open|Permissive (7)|Business friendly. Allows derivative works to choose their own license for their contributions.|
|Mozilla|Open|Weak Copyleft (13)|Allows liberal mixing with proprietary software.|
|MS Permissive|Open|Permissive (3)|Resembles the MIT and BSD licenses. Not formally accepted by OSI, and also offered in a "Windows-only" LPL variant.|
|MS Community|Open|Copyleft (3)|Resembles the GPL license. Requires all contributed code to be returned to the community. Not formally accepted by OSI, and also offered in a "Windows-only" LCL version.|
|MS Reference|Proprietary|Read Only (3)|You can review the code, or make copies of it, but you can't use it or change it in any way. Allows a window (no pun intended) on formerly completely proprietary, secret code.|

**Comment by JulienRobitaille** [comment]
Il y a aussi ce site: https://tldrlegal.com/ qui est super

**Comment by aubguillemette** [comment]
Moi, j'opte pour BSD ou GPL.

**Comment by BinaryTiger** [comment]
+1 pour [GPL3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

**Comment by AXDOOMER** [comment]
C'est quoi ça ce question là??? Choisir une license???? Y'aurait-il des hérétiques dans le club?? Cedille c'est un club de logiciels libres, pas un club de logiciels open source bidons à la noix. :boom:  :gun: 

![https://i.imgur.com/jrdP0ol.jpg](https://i.imgur.com/jrdP0ol.jpg)
**Choisi ta license. GPL3 ou GTFO.**

**Comment by AXDOOMER** [comment]
Sur une touche plus sérieuse, faut faire certain de ne pas copier du code sur stackoverflow ou d'un autre auteur pour mettre ça sous GPL, sinon c'est du copyright infringement.

**Comment by mikefaille** [comment]
Pour le `copyright infringement`, ça l'est aussi sans que ça soit GPLv3 en principe. Pour être stricte avec la loi, tout le code est prioritaire s'il n'a pas une licence déterminé.

**Comment by AXDOOMER** [comment]
Dans ce cas là je trouve ça important, car la distribuer sous une license implique qu'on va mettre notre nom dans le copyright header.

**Comment by AXDOOMER** [comment]
# VOTE
@aubguillemette @xavsavage @AlexBrochu @BinaryTiger @cmccauley 

*Je crois avoir tagué tous les membres du projet, mais au cas où j'en aurais oublié un, veuillez le taguer.*

Utilisez la réaction :+1: pour voter **OUI** pour la GPL3 ou :-1: pour voter **NON** sur ce commentaire. 

Si le vote **NON** gagne, nous discuterons d'un autre license. Le vote se porte sur la GPL3, car elle semble être la plus populaire dans ce issue. 

Le vote se termine le 23 juin ou dès que tous les gens tagués auront voté.

**Comment by mikefaille** [comment]
GPL3 implying GPL3+?
(juste comme ça)

**Comment by AXDOOMER** [comment]
J'ai modifié le vote, comme seulement toi et moi avons voté et nous semblons être d'accord. 

Ce sera donc GPL3+.

**Comment by aubguillemette** [comment]
tfw @AXDOOMER call un vote à 2h du mat... ;)

**Comment by AXDOOMER** [comment]
Je pense bien que c'est **GPL3+** qui a gagné. Le code source doit être mis sous cette license pour la sortie du prototype.

**Comment by AXDOOMER** [comment]
Il ne reste plus qu'à ajouter les GPL3+ headers à nos fichiers source respectifs.

**Comment by AXDOOMER** [comment]
Je ferme ça. C'est la responsabilité des membres d'ajouter leurs copyright headers au code qu'ils écrivent.
