### ISSUE TITLE
[API][NODE] Tests (acceptance, unitaire)

### ISSUE THREAD

**Issue by xavsavage** [ClubCedille/jardiniot#46]
Ça me brise le coeur de pas avoir 140 tests à exécuter juste pour voir qu'ils ont tous réussi avant de faire un push.

Donc:
- fixtures pour la base de données
- écrire une suite de tests pour l'api

**Comment by mikefaille** [comment]
💔

**Comment by notarock** [comment]
Ca reste toujours d'actualité. J'en prend contrôle puisque je m'enligne pour retravailler l'API.

**Comment by mikefaille** [comment]
Essaie jest er puppeteer

**Comment by AXDOOMER** [comment]
Ça serait hot que l'API puisse effectuer des tests sur le Jardin. Le code du Arduino n'a pas la capacité de se tester lui-même. Les tests sont Ad-hoc.

**Comment by AXDOOMER** [comment]
Fermé en faveur de https://github.com/ClubCedille/jardiniot/issues/70
