### ISSUE TITLE
[ARDUINO] Faire fonctionner les DELs

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/jardiniot#49]
On n'a pas le code source pour les DELs, il faut donc trouver leur fonctionnement. Elles doivent être contrôlées à partir des commandes reçues par MQTT. 

![http://www.richardvannoy.info/labs/lab-04/images/04-hookup-1.jpg](https://circuitdigest.com/sites/default/files/inlineimages/Arduino-PWM-Pins.jpg)

https://github.com/kiwisincebirth/Arduino/blob/master/libraries/PWMFrequency/PWMFrequency.h
http://playground.arduino.cc/Code/PwmFrequency
http://playground.arduino.cc/Main/TimerPWMCheatsheet
https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM
https://github.com/ClubCedille/jardiniot/issues/21#issuecomment-294951640
https://www.arduino.cc/en/Tutorial/PWM
https://www.farnell.com/datasheets/1682209.pdf

**Comment by AXDOOMER** [comment]
Ça fonctionne avec le code suivant:
```
void setup() {
  // DELs -- 0 => fermé, 1 (faible intensité) à 170 (très fortes)
  // -- Les pins 9, 10 et 11 sotn des pines PWM
  analogWrite(9, 1);   // blanches
  analogWrite(10, 1);  // bleues
  analogWrite(11, 1);  // rouges
  
  // VENTILATEURS -- 0-127 => fermé, 128-255 => tourne
  analogWrite(8, 255);  // fan sur le heatsink. 
  analogWrite(7, 255);  // fan d'ordi sur le coté du bucket
}

void loop() {
  // rien
}
```

**Comment by AXDOOMER** [comment]
J'ai plugué les fans dans des pins [PWM](https://www.arduino.cc/en/Tutorial/PWM), mais si la valeur n'est pas exactement 255 pour la faire tourner, on peut entendre du bruit électronique dedans, ce qui est très dérangeant. 

```
void setup() {
  // Les pins 5, 6, 9, 10, 11 reçoivent des PWM
  
  // DELs -- les valeurs données règlent l'intensité
  analogWrite(9, 1);   // blanches
  analogWrite(10, 1);  // bleues
  analogWrite(11, 1);  // rouges
  
  // VENTILATEURS -- la valeurs données règlent leur vitesse
  analogWrite(6, 255);  // fan sur le heatsink. 
  analogWrite(5, 255);  // fan d'ordi sur le coté du bucket
}

void loop() {
  // rien
}
```

**Comment by AXDOOMER** [comment]
@cmccauley T'as fait une belle job avec l'électronique. J'ai pas eu de la misère du tout à faire fonctionner ça. 

Je passe maintenant à l'intégration de mon code dans le programme principal.

**Comment by AXDOOMER** [comment]
Nouvelle configuration: 

![100_1001](https://user-images.githubusercontent.com/6194072/27569591-586d9e14-5ac6-11e7-84e3-aae1b1a8ca52.JPG)

Le ESP est connecté comme d'habitude: 

![100_1000](https://user-images.githubusercontent.com/6194072/27569600-605a8f24-5ac6-11e7-832a-4cd6436e6b83.JPG)

En général, ça l'air de ça:

![100b1030](https://user-images.githubusercontent.com/6194072/27569619-77e15bdc-5ac6-11e7-8eaf-ccd755f281f3.JPG)

Les senseurs et les DELs sont tous connectés ici pour le data: 

![100b0990](https://user-images.githubusercontent.com/6194072/27569624-7df4095c-5ac6-11e7-850b-816ecd11edf9.JPG)

De l'autre côté ça reste pareil:

![100b1050](https://user-images.githubusercontent.com/6194072/27569645-a441bf64-5ac6-11e7-9714-94885028760d.JPG)

Faut être certain que le ventilateur latéral et le grand ventilateur soient bien connectés. (voir: le label reset qui fait face à la caméra et le fil jaune du grand ventilateur qui n'est connectés à aucune pin, car il y a juste 2 pins pour lui aussi comme l'autre). 

![100b1020](https://user-images.githubusercontent.com/6194072/27569654-b2fe2268-5ac6-11e7-84d8-2c85d520ca18.JPG)

*Il n'y a aucun capaciteur pour le grand ventilateur, donc si on le fait pas tourner à 100% de sa vitesse, les PWM vont causer du bruit électronique dans l'air qu'on pourra entendre.

**Comment by mikefaille** [comment]
Intéressant!

**Comment by AXDOOMER** [comment]
En attente de correction d'un bug avant de tester officiellement le https://github.com/ClubCedille/jardiniot/pull/50 et de fermer ce issue.

**Comment by AXDOOMER** [comment]
Comme le code a été testé dans un programme de test indépendant et qu'il marchait, je ferme ce issue.
