### ISSUE TITLE
Retirer la branche "front-end" du répo de Cedille

### ISSUE THREAD

**Issue by notarock** [ClubCedille/jardiniot#64]
C'est une vielle branche que j'utilisais avant qu'on utilise les forks et les pull request comme workflow. 
Puisque le panneau de contrôle a été ajouté à la branche master, elle peut être supprimé.

**Comment by AXDOOMER** [comment]
Effacé. Merci!

https://github.com/ClubCedille/jardiniot/tree/frontend
